### ISSUE TITLE
Error message while starting up

### ISSUE THREAD

**Issue by PaulZH** [stkenny/grefine-rdf-extension#29] opened 2019-08-02 11:46 UTC
Error message while starting up after installing the 3.2 RDF extension in Openrefine 3.2.
```
Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module rdf-extension [edu.mit.simile.butterfly.ButterflyModuleImpl]
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:291)
	at com.google.refine.RefineServer.init(Refine.java:203)
	at com.google.refine.Refine.init(Refine.java:109)
	at com.google.refine.Refine.main(Refine.java:103)
Caused by: org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (file:/Users/pzh/Library/Application%20Support/OpenRefine/extensions/rdf-extension/MOD-INF/controller.js#89)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1932)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.file__Users_pzh_Library_Application_20Support_OpenRefine_extensions_rdf_extension_MOD_INF_controller_js_10._c_init_4(file:/Users/pzh/Library/Application%20Support/OpenRefine/extensions/rdf-extension/MOD-INF/controller.js:89)
	at org.mozilla.javascript.gen.file__Users_pzh_Library_Application_20Support_OpenRefine_extensions_rdf_extension_MOD_INF_controller_js_10.call(file:/Users/pzh/Library/Application%20Support/OpenRefine/extensions/rdf-extension/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.file__Users_pzh_Library_Application_20Support_OpenRefine_extensions_rdf_extension_MOD_INF_controller_js_10.call(file:/Users/pzh/Library/Application%20Support/OpenRefine/extensions/rdf-extension/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	... 8 more
Caused by: java.lang.NullPointerException
	at org.deri.grefine.rdf.vocab.imp.VocabularySearcher.<init>(VocabularySearcher.java:80)
	at org.deri.grefine.rdf.app.ApplicationContext.init(ApplicationContext.java:30)
	at org.deri.grefine.rdf.app.InitializationCommand.initRdfExportApplicationContext(InitializationCommand.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 18 more
```

**Comment by stkenny** [comment] 2019-08-02 17:57
Should be fixed in https://github.com/stkenny/grefine-rdf-extension/releases/tag/v1.1.3-orefine-3.2

**Comment by PaulZH** [comment] 2019-08-02 18:16
Indeed, solved.

**Comment by sk-hdm** [comment] 2019-08-14 10:56
I seem to be getting the same error as above. Have latest OR installed and the updated 1.1.3 rdf extension.

`Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module rdf-extension [edu.mit.simile.butterfly.ButterflyModuleImpl]
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:291)
	at com.google.refine.RefineServer.init(Refine.java:203)
	at com.google.refine.Refine.init(Refine.java:109)
	at com.google.refine.Refine.main(Refine.java:103)
Caused by: org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (file:/C:/Users/SK/AppData/Local/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js#89)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1932)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.file__C__Users_SK_AppData_Local_OpenRefine_extensions_rdf_extension_module_MOD_INF_controller_js_10._c_init_4(file:/C:/Users/SK/AppData/Local/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js:89)
	at org.mozilla.javascript.gen.file__C__Users_SK_AppData_Local_OpenRefine_extensions_rdf_extension_module_MOD_INF_controller_js_10.call(file:/C:/Users/SK/AppData/Local/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.file__C__Users_SK_AppData_Local_OpenRefine_extensions_rdf_extension_module_MOD_INF_controller_js_10.call(file:/C:/Users/SK/AppData/Local/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	... 8 more
Caused by: java.lang.NullPointerException
	at org.deri.grefine.rdf.vocab.imp.PredefinedVocabularyManager.load(PredefinedVocabularyManager.java:135)
	at org.deri.grefine.rdf.vocab.imp.PredefinedVocabularyManager.reconstructVocabulariesFromFile(PredefinedVocabularyManager.java:93)
	at org.deri.grefine.rdf.vocab.imp.PredefinedVocabularyManager.<init>(PredefinedVocabularyManager.java:46)
	at org.deri.grefine.rdf.app.ApplicationContext.init(ApplicationContext.java:31)
	at org.deri.grefine.rdf.app.InitializationCommand.initRdfExportApplicationContext(InitializationCommand.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 18 more`

**Comment by stkenny** [comment] 2019-08-18 17:20
Issue with 3.2 branch. Created new issue.

**Closed by stkenny** 2019-08-18 17:20 UTC
