### ISSUE TITLE
ERROR 500

### ISSUE THREAD

**Issue by Liuyan661** [stkenny/grefine-rdf-extension#23] opened 2019-04-03 14:53 UTC
When I install the rdf extension, I encounter this error. Can you help me?
===================================
HTTP ERROR 500
Problem accessing /. Reason:

    Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module rdf-extension [edu.mit.simile.butterfly.ButterflyModuleImpl]
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:291)
	at com.google.refine.RefineServer.init(Refine.java:203)
	at com.google.refine.Refine.init(Refine.java:109)
	at com.google.refine.Refine.main(Refine.java:103)
Caused by: org.mozilla.javascript.EvaluatorException: Can't find method com.google.refine.RefineServlet.cacheClass(object). (file:/C:/Program%20Files%20(x86)/openrefine-3.1/webapp/extensions/rdf-extension/src/main/resources/module/MOD-INF/controller.js#82)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:998)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:1053)
	at org.mozilla.javascript.Context.reportRuntimeError1(Context.java:1016)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:144)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.file__C__Program_20Files_20_x86__openrefine_3_1_webapp_extensions_rdf_extension_src_main_resources_module_MOD_INF_controller_js_8._c_init_4(file:/C:/Program%20Files%20(x86)/openrefine-3.1/webapp/extensions/rdf-extension/src/main/resources/module/MOD-INF/controller.js:82)
	at org.mozilla.javascript.gen.file__C__Program_20Files_20_x86__openrefine_3_1_webapp_extensions_rdf_extension_src_main_resources_module_MOD_INF_controller_js_8.call(file:/C:/Program%20Files%20(x86)/openrefine-3.1/webapp/extensions/rdf-extension/src/main/resources/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.file__C__Program_20Files_20_x86__openrefine_3_1_webapp_extensions_rdf_extension_src_main_resources_module_MOD_INF_controller_js_8.call(file:/C:/Program%20Files%20(x86)/openrefine-3.1/webapp/extensions/rdf-extension/src/main/resources/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	... 8 more

**Comment by stkenny** [comment] 2019-04-03 16:28
Hi, it looks like maybe the source code of the extension is in the extension folder rather than the compiled release? Could you install from https://github.com/stkenny/grefine-rdf-extension/releases/download/v1.1.0/grefine-rdf-extension-1.1.0-openrefine-module.zip instead. Remove the contents of the rdf-extension folder and replace with the extracted contents of the zip.

**Comment by paigecm** [comment] 2019-04-03 20:11
I'm getting the same error as Liuyan661. I tried following your instructions to make sure that the source code was in the right place -- so in the OpenRefine folder under AppData I have extensions/rdf-extension/module, and then the folders from the release version you link to above (1.1.0).

Any suggestions? Thanks very much in advance.

Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module rdf-extension [edu.mit.simile.butterfly.ButterflyModuleImpl]
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:291)
	at com.google.refine.RefineServer.init(Refine.java:203)
	at com.google.refine.Refine.init(Refine.java:109)
	at com.google.refine.Refine.main(Refine.java:103)
Caused by: org.mozilla.javascript.WrappedException: Wrapped org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\pmorgan\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex\segments_e"))): 0 (needs to be between 4 and 6). This version of Lucene only supports indexes created with release 5.0 and later. (file:/C:/Users/pmorgan/AppData/Roaming/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js#89)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1932)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.file__C__Users_pmorgan_AppData_Roaming_OpenRefine_extensions_rdf_extension_module_MOD_INF_controller_js_8._c_init_4(file:/C:/Users/pmorgan/AppData/Roaming/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js:89)
	at org.mozilla.javascript.gen.file__C__Users_pmorgan_AppData_Roaming_OpenRefine_extensions_rdf_extension_module_MOD_INF_controller_js_8.call(file:/C:/Users/pmorgan/AppData/Roaming/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.file__C__Users_pmorgan_AppData_Roaming_OpenRefine_extensions_rdf_extension_module_MOD_INF_controller_js_8.call(file:/C:/Users/pmorgan/AppData/Roaming/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	... 8 more
Caused by: org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\pmorgan\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex\segments_e"))): 0 (needs to be between 4 and 6). This version of Lucene only supports indexes created with release 5.0 and later.
	at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:213)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:302)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:286)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:938)
	at org.deri.grefine.rdf.vocab.imp.VocabularySearcher.<init>(VocabularySearcher.java:74)
	at org.deri.grefine.rdf.app.ApplicationContext.init(ApplicationContext.java:31)
	at org.deri.grefine.rdf.app.InitilizationCommand.initRdfExportApplicationContext(InitilizationCommand.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 18 more

**Comment by Liuyan661** [comment] 2019-04-04 00:56
> Hi, it looks like maybe the source code of the extension is in the extension folder rather than the compiled release? Could you install from https://github.com/stkenny/grefine-rdf-extension/releases/download/v1.1.0/grefine-rdf-extension-1.1.0-openrefine-module.zip instead. Remove the contents of the rdf-extension folder and replace with the extracted contents of the zip.

I replaced the file, but encountered another error.
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:161)
        at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:151)
        at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:144)
        at org.apache.tika.config.TikaConfig.<init>(TikaConfig.java:140)
        at org.apache.any23.mime.TikaMIMETypeDetector.<init>(TikaMIMETypeDetector.java:204)
        at org.apache.any23.Any23.<init>(Any23.java:83)
        at org.apache.any23.Any23.<init>(Any23.java:130)
        at org.apache.any23.Any23.<init>(Any23.java:154)
        at org.apache.any23.Any23.<init>(Any23.java:161)
        at org.deri.grefine.rdf.vocab.VocabularyImporter.getModel(VocabularyImporter.java:75)
        at org.deri.grefine.rdf.vocab.VocabularyImporter.importVocabulary(VocabularyImporter.java:30)
        at org.deri.grefine.rdf.vocab.imp.VocabularySearcher.importAndIndexVocabulary(VocabularySearcher.java:90)
        at org.deri.grefine.rdf.vocab.imp.VocabularySearcher.importAndIndexVocabulary(VocabularySearcher.java:82)
        at org.deri.grefine.rdf.vocab.imp.PredefinedVocabularyManager.addPredefinedVocabularies(PredefinedVocabularyManager.java:71)
        at org.deri.grefine.rdf.vocab.imp.PredefinedVocabularyManager.<init>(PredefinedVocabularyManager.java:46)
        at org.deri.grefine.rdf.app.ApplicationContext.init(ApplicationContext.java:32)
        at org.deri.grefine.rdf.app.InitilizationCommand.initRdfExportApplicationContext(InitilizationCommand.java:38)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
        at org.mozilla.javascript.gen.file__D__MoreProgram_openrefine_3_1_webapp_extensions_rdf_extension_module_MOD_INF_controller_js_8._c_init_4(file:/D:/MoreProgram/openrefine-3.1/webapp/extensions/rdf-extension/module/MOD-INF/controller.js:89)
        at org.mozilla.javascript.gen.file__D__MoreProgram_openrefine_3_1_webapp_extensions_rdf_extension_module_MOD_INF_controller_js_8.call(file:/D:/MoreProgram/openrefine-3.1/webapp/extensions/rdf-extension/module/MOD-INF/controller.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
        at org.mozilla.javascript.gen.file__D__MoreProgram_openrefine_3_1_webapp_extensions_rdf_extension_module_MOD_INF_controller_js_8.call(file:/D:/MoreProgram/openrefine-3.1/webapp/extensions/rdf-extension/module/MOD-INF/controller.js)
        at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
        at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
        at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
        at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
        at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
        at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
        at com.google.refine.RefineServer.configure(Refine.java:291)
        at com.google.refine.RefineServer.init(Refine.java:203)
        at com.google.refine.Refine.init(Refine.java:109)
        at com.google.refine.Refine.main(Refine.java:103)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at edu.mit.simile.butterfly.ButterflyClassLoader.loadClass(ButterflyClassLoader.java:65)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 40 more
```

**Comment by stkenny** [comment] 2019-04-04 07:24
> I'm getting almost the same error as Liuyan661. I tried following your instructions to make sure that the source code was in the right place -- so in the OpenRefine folder under AppData I have extensions/rdf-extension/module, and then the folders from the release version you link to above (1.1.0).
> 
> Any suggestions? Thanks very much in advance.
> **ETA:** I tried a few different configurations, hoping to get it right -- having extensions/rdf-extension/module/... (which works beautifully on my Mac), putting the unzipped grefine-rdf-extension folder inside rdf-extension; and putting the contents of the module folder inside the rdf-extension folder. All of those configurations lead to the same error, sadly.
> 
> Butterfly Error
> Butterfly incurred in the following errors while initializing:
> java.lang.Exception: Failed to initialize module rdf-extension [edu.mit.simile.butterfly.ButterflyModuleImpl]
> at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
> at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
> at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
> at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
> at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
> at com.google.refine.RefineServer.configure(Refine.java:291)
> at com.google.refine.RefineServer.init(Refine.java:203)
> at com.google.refine.Refine.init(Refine.java:109)
> at com.google.refine.Refine.main(Refine.java:103)
> Caused by: org.mozilla.javascript.WrappedException: Wrapped org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\pmorgan\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex\segments_e"))): 0 (needs to be between 4 and 6). This version of Lucene only supports indexes created with release 5.0 and later. (file:/C:/Users/pmorgan/AppData/Roaming/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js#89)
> at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1932)
> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
> at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
> at org.mozilla.javascript.gen.file__C__Users_pmorgan_AppData_Roaming_OpenRefine_extensions_rdf_extension_module_MOD_INF_controller_js_8._c_init_4(file:/C:/Users/pmorgan/AppData/Roaming/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js:89)
> at org.mozilla.javascript.gen.file__C__Users_pmorgan_AppData_Roaming_OpenRefine_extensions_rdf_extension_module_MOD_INF_controller_js_8.call(file:/C:/Users/pmorgan/AppData/Roaming/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js)
> at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
> at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
> at org.mozilla.javascript.gen.file__C__Users_pmorgan_AppData_Roaming_OpenRefine_extensions_rdf_extension_module_MOD_INF_controller_js_8.call(file:/C:/Users/pmorgan/AppData/Roaming/OpenRefine/extensions/rdf-extension/module/MOD-INF/controller.js)
> at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
> at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
> at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
> ... 8 more
> Caused by: org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="C:\Users\pmorgan\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex\segments_e"))): 0 (needs to be between 4 and 6). This version of Lucene only supports indexes created with release 5.0 and later.
> at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:213)
> at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:302)
> at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:286)
> at org.apache.lucene.index.IndexWriter.(IndexWriter.java:938)
> at org.deri.grefine.rdf.vocab.imp.VocabularySearcher.(VocabularySearcher.java:74)
> at org.deri.grefine.rdf.app.ApplicationContext.init(ApplicationContext.java:31)
> at org.deri.grefine.rdf.app.InitilizationCommand.initRdfExportApplicationContext(InitilizationCommand.java:38)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
> ... 18 more

@paigecm HI, this is a different error caused by an update to the Lucene version. If you delete C:\Users\pmorgan\AppData\Roaming\OpenRefine\cache\rdfExtension\export\luceneIndex and restart the error should be fixed. Thanks.

**Comment by paigecm** [comment] 2019-04-04 15:03
@stkenny Thank you so much! That fixed it!

**Closed** 2019-04-04 16:37 UTC
