### ISSUE TITLE
Cannot add RDF reconciliation service

### ISSUE THREAD

**Issue by PaulZH** [stkenny/grefine-rdf-extension#33] opened 2019-10-09 11:10 UTC
OpenRefine 3.2
RDF extension version 1.1.5
Mac OS Mojave

Both adding:
- a RDF file based reconciliation service
- a SPARQL endpoint based reconciliation service
runs for ever (see screendumps).

How to find out what is causing this?

![Screenshot 2019-10-09 at 12 46 33](https://user-images.githubusercontent.com/437781/66476428-dff65400-ea95-11e9-87e1-b0a188cccb10.png)
<img width="606" alt="Screenshot 2019-10-09 at 12 54 13" src="https://user-images.githubusercontent.com/437781/66476429-dff65400-ea95-11e9-8923-3512e3add96c.png">

**Comment by rlgunt2001** [comment] 2019-10-09 13:52
I tried doing the same thing a few weeks ago and encountered the
same problem.   It ran for a very long stretch of time and I eventually
closed it.  Since I was doing this as a way of testing/experimenting and
life's been quite busy lately - I did not get around to reporting this....

but since this is being asked... Just wanted to say, 'me too'.  I'd like to
hear any solutions or workarounds.
Thanks
Richard

**Comment by stkenny** [comment] 2019-10-10 18:53
I won't have a decent internet connection until next week, so will get a fix released then. Without an error log it is hard to say what the issue is, but I would suspect another problem caused by the change in JSON library.

**Comment by stkenny** [comment] 2019-10-20 09:38
Fixed in v1.1.6

**Closed by stkenny** 2019-10-20 09:38 UTC

**Comment by rlgunt2001** [comment] 2019-10-20 22:57
Thank you so very much!  I'm trying to download the latest release v.1.1.6 but I keep getting the v.1.1.5
How can I get the v.1.1.6?
Thank you again
Richard

**Comment by stkenny** [comment] 2019-10-21 05:26
Sorry, link on README was wrong, it is here https://github.com/stkenny/grefine-rdf-extension/releases/tag/v1.1.6-orefine-3.2

**Comment by rlgunt2001** [comment] 2019-10-21 13:33
Fabulous and thank you!
